### ISSUE TITLE
App breaks when a news from data provider maz is rendered

### ISSUE THREAD

**Issue by acousma82** [smart-village-solutions/smart-village-app#15]
When clicking on a maz news the app breaks:

![Screenshot_20190621-171129_Bad Belzig App](https://user-images.githubusercontent.com/31201899/59932720-186f1500-9448-11e9-9cb1-ace6752b530c.jpg)
![Screenshot_20190621-171145_Bad Belzig App](https://user-images.githubusercontent.com/31201899/59932717-17d67e80-9448-11e9-85ea-106eb9a2189c.jpg)
![Screenshot_20190621-171201_Bad Belzig App](https://user-images.githubusercontent.com/31201899/59932716-17d67e80-9448-11e9-9c83-b63349609b83.jpg)

**Comment by acousma82** [comment]
After discussing with @donni106  i added a logo url for the maz data provider. But this didn't help the app still breaks

**Comment by donni106** [comment]
Did you use the Expo app or from Google Play store?
Try to clear your cache of the app and start again. The error looks like before added a logo with url. There should be no `null` anymore.

**Comment by donni106** [comment]
Will be fixed in **0.8.6**.
